In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

# Sample model with dropout
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 500)
        self.fc2 = nn.Linear(500, 10)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x


In [ ]:
# Generating random sample data: 5 samples with 784 features each
input_data = torch.randn(5, 784)


In [ ]:
model = Net()
model.train()  # Ensure the model is in training mode

features_after_dropout = F.relu(model.fc1(input_data))
features_after_dropout = model.dropout(features_after_dropout)
print("Features after dropout during training:")
print(features_after_dropout)
print(features_after_dropout.shape)


Features after dropout during training:
tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [1.9237, 0.0000, 0.0000,  ..., 1.3639, 0.0000, 0.0000],
        [0.0000, 0.0000, 1.2972,  ..., 0.0000, 0.3022, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 1.4781, 0.0000],
        [0.9912, 0.0000, 0.0000,  ..., 0.0000, 1.8814, 0.0000]],
       grad_fn=<MulBackward0>)
torch.Size([5, 500])


In [ ]:
model.eval()  # Ensure the model is in eval mode

features_without_dropout = F.relu(model.fc1(input_data))
print("\nFeatures without dropout during inference:")
print(features_without_dropout)
print(features_without_dropout.shape)


Features without dropout during inference:
tensor([[0.5827, 0.0000, 0.0000,  ..., 0.0160, 0.0000, 0.0000],
        [0.9619, 0.0000, 0.0000,  ..., 0.6820, 0.0000, 0.0000],
        [0.0000, 0.0186, 0.6486,  ..., 0.0000, 0.1511, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.7390, 0.0000],
        [0.4956, 0.8977, 0.0000,  ..., 0.0000, 0.9407, 0.4167]],
       grad_fn=<ReluBackward0>)
torch.Size([5, 500])


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

# Sample model with dropout
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 500)
        self.fc2 = nn.Linear(500, 10)
        self.dropout = nn.Dropout(0.5)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.fc2(x)
        return x


In [ ]:
# Generating random sample data: 5 samples with 784 features each
input_data = torch.randn(5, 784)


In [ ]:
model = Net()
model.train()  # Ensure the model is in training mode

# Get features before and after dropout
features_before_dropout = F.relu(model.fc1(input_data))
features_after_dropout = model.dropout(features_before_dropout)

# Identifying dropped features
dropped_features = features_before_dropout - features_after_dropout
dropped_indices = (dropped_features != 0).nonzero(as_tuple=True)

print("Indices of dropped features:")
print(dropped_indices)


Indices of dropped features:
(tensor([0, 0, 0,  ..., 4, 4, 4]), tensor([  1,   2,   8,  ..., 495, 497, 499]))


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

# 1. Sample Data
input_data = np.random.randn(1000, 784)
labels = np.random.randint(10, size=(1000,))

# 2. Custom Dropout Layer
class CustomDropout(keras.layers.Dropout):
    def call(self, inputs, training=None):
        if training:
            binary_dropout_mask = tf.nn.dropout(
                tf.ones_like(inputs), rate=self.rate)
            dropped_indices = tf.where(binary_dropout_mask == 0)
            tf.print(f"Dropped Indices: {dropped_indices}")
            return inputs * binary_dropout_mask
        return inputs

# 3. Define the Model Using CustomDropout
model = keras.Sequential([
    keras.layers.Dense(500, activation='relu', input_shape=(784,)),
    CustomDropout(0.5),
    keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy')

# 4. Train the Model
model.fit(input_data, labels, epochs=5, batch_size=32)


Epoch 1/5
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
 1/32 [..............................] - ETA: 58s - loss: 3.1112Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
 5/32 [===>..........................] - ETA: 0s - loss: 3.1462 Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("sequential_2/custom_dropout/Where:0", shape=(None, 2), dtype=int64)
Dropped Indices: Tensor("